BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TASIGNADOA" (
	"id_cita"	INTEGER,
	"id_medico"	INTEGER,
	PRIMARY KEY("id_cita","id_medico"),
	FOREIGN KEY("id_cita") REFERENCES "TCITAS"("id"),
	FOREIGN KEY("id_medico") REFERENCES "TMEDICOS"("ID")
);
CREATE TABLE IF NOT EXISTS "TENFERMEROS" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"NOMBRE"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TJORNADALABORAL" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"NOMBRE_TRABAJADOR"	TEXT NOT NULL,
	"DIA_COMIENZO"	TEXT NOT NULL,
	"HORA_ENTRADA"	TEXT NOT NULL,
	"DIA_FIN"	TEXT NOT NULL,
	"HORA_SALIDA"	TEXT NOT NULL,
	"LUNES"	INTEGER DEFAULT 0,
	"MARTES"	INTEGER DEFAULT 0,
	"MIERCOLES"	INTEGER DEFAULT 0,
	"JUEVES"	INTEGER DEFAULT 0,
	"VIERNES"	INTEGER DEFAULT 0,
	"SABADO"	INTEGER DEFAULT 0,
	"DOMINGO"	INTEGER DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TPACIENTES" (
	"ID"	INTEGER NOT NULL,
	"NOMBRE"	TEXT,
	"info_contacto"	TEXT,
	"apellido"	TEXT,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "THISTORIALES" (
	"idPaciente"	INTEGER,
	"vacunas"	TEXT,
	"antecedentes"	TEXT,
	"informacionAdicional"	TEXT,
	PRIMARY KEY("idPaciente"),
	FOREIGN KEY("idPaciente") REFERENCES "TPACIENTES"("id")
);
CREATE TABLE IF NOT EXISTS "TCAUSA" (
	"OBSERVATIONS"	TEXT,
	"DATE"	TEXT NOT NULL,
	"HOUR"	TEXT NOT NULL,
	"NAME"	TEXT NOT NULL,
	"ID"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "TMEDICOS" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"NOMBRE"	TEXT,
	"ESPECIALIDAD"	TEXT,
	"EMAIL"	TEXT,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "TPRESCRIPCIONES" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"PACIENTE_ID"	INTEGER,
	"NOMBRE"	TEXT NOT NULL,
	"INDICACIONES"	TEXT NOT NULL,
	"MEDICAMENTO"	INTEGER,
	"CANTIDAD"	TEXT,
	"INTERVALO"	TEXT,
	"DURACION"	TEXT,
	"FECHA"	TEXT,
	"HORA"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TDIAGNOSTICOS" (
	"id"	INTEGER,
	"id_paciente"	INTEGER,
	"diagnostico"	TEXT,
	"fecha"	TEXT,
	"id_medico"	INTEGER,
	PRIMARY KEY("id"),
	FOREIGN KEY("id_medico") REFERENCES "TMEDICOS"("ID"),
	FOREIGN KEY("id_paciente") REFERENCES "TPACIENTES"("ID")
);
CREATE TABLE IF NOT EXISTS "TCITAS" (
	"id"	NUMERIC,
	"horario_inicio"	TEXT,
	"horario_fin"	TEXT,
	"ubicacion"	TEXT,
	"contacto"	TEXT,
	"id_paciente"	INTEGER NOT NULL,
	"id_medico"	BLOB,
	"acudio"	TEXT,
	"fecha"	TEXT,
	"Informacion"	TEXT,
	"especialidad"	TEXT,
	"hora_entrada"	TEXT,
	"hora_salida"	TEXT,
	"nombre_paciente"	TEXT,
	PRIMARY KEY("id"),
	FOREIGN KEY("id_paciente") REFERENCES "TPACIENTES"("ID"),
	FOREIGN KEY("id_medico") REFERENCES "TMEDICOS"("ID")
);
CREATE TABLE IF NOT EXISTS "TREGISTRO" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"QUIEN"	TEXT,
	"QUE"	TEXT,
	"FECHA"	TEXT,
	"HORA"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TCITASPENDIENTES" (
	"ID"	INTEGER,
	"HORA_ENTRADA"	TEXT,
	"HORA_SALIDA"	TEXT,
	"NOMBRE_PACIENTE"	TEXT,
	"NOMBRE_MEDICO"	TEXT,
	"UBICACION"	TEXT,
	"CONTACTO_MEDICO"	TEXT,
	"IDPACIENTE"	INTEGER,
	"ID_MEDICO"	INTEGER,
	"FECHA"	TEXT
);
COMMIT;
